In [227]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("andrewsundberg/college-basketball-dataset")

print("Path to dataset files:", path)

Path to dataset files: /Users/liufamily/.cache/kagglehub/datasets/andrewsundberg/college-basketball-dataset/versions/7


In [228]:
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd
import os


In [229]:
data=pd.read_csv('cbb.csv')
data

TEAM  CONF   G   W  ADJOE  ADJDE  BARTHAG  EFG_O  EFG_D   TOR  \
0     North Carolina   ACC  40  33  123.3   94.9   0.9531   52.6   48.1  15.4   
1          Wisconsin   B10  40  36  129.1   93.6   0.9758   54.8   47.7  12.4   
2           Michigan   B10  40  33  114.4   90.4   0.9375   53.9   47.7  14.0   
3         Texas Tech   B12  38  31  115.2   85.2   0.9696   53.5   43.0  17.7   
4            Gonzaga   WCC  39  37  117.8   86.3   0.9728   56.6   41.1  16.2   
...              ...   ...  ..  ..    ...    ...      ...    ...    ...   ...   
3518          Toledo   MAC  34  27  119.9  109.6   0.7369   56.3   52.9  13.6   
3519         Liberty  ASun  33  27  111.4   97.3   0.8246   55.5   49.3  16.0   
3520     Utah Valley   WAC  34  28  107.1   94.6   0.8065   51.7   44.0  19.3   
3521             UAB  CUSA  38  29  112.4   97.0   0.8453   50.3   47.3  17.3   
3522     North Texas  CUSA  36  31  110.0   93.8   0.8622   51.2   44.5  19.8   

      ...  FTRD  2P_O  2P_D  3P_O  3P_D  ADJ_T   WAB  POSTSEASON  SEED  YEAR  
0     ...  30.4  53.9  44.6  32.7  36.2   71.7   8.6         2ND   1.0  2016  
1     ...  22.4  54.8  44.7  36.5  37.5   59.3  11.3         2ND   1.0  2015  
2     ...  30.0  54.7  46.8  35.2  33.2   65.9   6.9         2ND   3.0  2018  
3     ...  36.6  52.8  41.9  36.5  29.7   67.5   7.0         2ND   3.0  2019  
4     ...  26.9  56.3  40.0  38.2  29.0   71.5   7.7         2ND   1.0  2017  
...   ...   ...   ...   ...   ...   ...    ...   ...         ...   ...   ...  
3518  ...  27.5  54.6  52.1  39.7  36.1   69.5  -1.2         NaN   NaN  2023  
3519  ...  27.8  56.4  48.6  36.4  33.6   64.4  -2.0         NaN   NaN  2023  
3520  ...  28.7  52.5  42.8  33.4  31.1   69.8  -0.3         NaN   NaN  2023  
3521  ...  28.9  48.8  47.2  35.6  31.6   70.7  -0.5         NaN   NaN  2023  
3522  ...  40.2  49.6  44.2  35.7  30.1   58.7   1.1         NaN   NaN  2023  

[3523 rows x 24 columns]

In [230]:
value_mapping = {
    np.nan: 0,
    "R68": 1,
    "R64": 2,
    "R32": 3,
    "S16": 4,
    "E8": 5,
    "F4": 6,
    "2ND": 7,
    "Champions": 8
}
data_cleaned = data.copy()
data_cleaned2 = data_cleaned.drop(['TEAM', 'G', 'W', 'CONF', 'YEAR', 'WAB'], axis=1)
data_cleaned['POSTSEASON'] = data_cleaned["POSTSEASON"].replace(value_mapping)
data_cleaned2['POSTSEASON'] = data_cleaned2["POSTSEASON"].replace(value_mapping)

data_cleaned = pd.get_dummies(data_cleaned, columns=['CONF'])
data_cleaned = pd.get_dummies(data_cleaned, columns=['YEAR'])
data_cleaned = data_cleaned.drop(['TEAM', 'G', 'W'], axis=1)
data_cleaned = data_cleaned.astype(float)
data_cleaned2 = data_cleaned2.astype(float)
data_cleaned2.fillna(0.0, inplace=True)
data_cleaned

/var/folders/q0/hn6y49dn3qlbbv0j58dc42tm0000gn/T/ipykernel_39806/2438171600.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_cleaned['POSTSEASON'] = data_cleaned["POSTSEASON"].replace(value_mapping)
/var/folders/q0/hn6y49dn3qlbbv0j58dc42tm0000gn/T/ipykernel_39806/2438171600.py:15: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_cleaned2['POSTSEASON'] = data_cleaned2["POSTSEASON"].replace(value_mapping)


ADJOE  ADJDE  BARTHAG  EFG_O  EFG_D   TOR  TORD   ORB   DRB   FTR  ...  \
0     123.3   94.9   0.9531   52.6   48.1  15.4  18.2  40.7  30.0  32.3  ...   
1     129.1   93.6   0.9758   54.8   47.7  12.4  15.8  32.1  23.7  36.2  ...   
2     114.4   90.4   0.9375   53.9   47.7  14.0  19.5  25.5  24.9  30.7  ...   
3     115.2   85.2   0.9696   53.5   43.0  17.7  22.8  27.4  28.7  32.9  ...   
4     117.8   86.3   0.9728   56.6   41.1  16.2  17.1  30.0  26.2  39.0  ...   
...     ...    ...      ...    ...    ...   ...   ...   ...   ...   ...  ...   
3518  119.9  109.6   0.7369   56.3   52.9  13.6  18.3  29.8  30.9  34.4  ...   
3519  111.4   97.3   0.8246   55.5   49.3  16.0  18.9  25.3  20.2  26.2  ...   
3520  107.1   94.6   0.8065   51.7   44.0  19.3  16.3  28.9  29.1  35.6  ...   
3521  112.4   97.0   0.8453   50.3   47.3  17.3  19.3  35.8  29.3  35.7  ...   
3522  110.0   93.8   0.8622   51.2   44.5  19.8  19.9  33.4  28.6  31.0  ...   

      YEAR_2013  YEAR_2014  YEAR_2015  YEAR_2016  YEAR_2017  YEAR_2018  \
0           0.0        0.0        0.0        1.0        0.0        0.0   
1           0.0        0.0        1.0        0.0        0.0        0.0   
2           0.0        0.0        0.0        0.0        0.0        1.0   
3           0.0        0.0        0.0        0.0        0.0        0.0   
4           0.0        0.0        0.0        0.0        1.0        0.0   
...         ...        ...        ...        ...        ...        ...   
3518        0.0        0.0        0.0        0.0        0.0        0.0   
3519        0.0        0.0        0.0        0.0        0.0        0.0   
3520        0.0        0.0        0.0        0.0        0.0        0.0   
3521        0.0        0.0        0.0        0.0        0.0        0.0   
3522        0.0        0.0        0.0        0.0        0.0        0.0   

      YEAR_2019  YEAR_2021  YEAR_2022  YEAR_2023  
0           0.0        0.0        0.0        0.0  
1           0.0        0.0        0.0        0.0  
2           0.0        0.0        0.0        0.0  
3           1.0        0.0        0.0        0.0  
4           0.0        0.0        0.0        0.0  
...         ...        ...        ...        ...  
3518        0.0        0.0        0.0        1.0  
3519        0.0        0.0        0.0        1.0  
3520        0.0        0.0        0.0        1.0  
3521        0.0        0.0        0.0        1.0  
3522        0.0        0.0        0.0        1.0  

[3523 rows x 64 columns]

In [231]:
data_cleaned_no_seed = data_cleaned.drop('SEED', axis=1)

In [232]:
X_data_array = data_cleaned.drop("POSTSEASON", axis=1).to_numpy()
X_data_array_no_seed = data_cleaned_no_seed.drop("POSTSEASON", axis=1).to_numpy()
X_data_array2 = data_cleaned2.drop("POSTSEASON", axis=1).to_numpy()
X_data_array = np.nan_to_num(X_data_array) 
X_data_array_no_seed = np.nan_to_num(X_data_array_no_seed) 
X_data_array.shape

(3523, 63)

In [233]:
y_labels_array = data_cleaned['POSTSEASON'].to_numpy()
y_labels_array

array([7., 7., 7., ..., 0., 0., 0.])

In [234]:
X_train, X_test, y_train, y_test = train_test_split(X_data_array, y_labels_array, test_size=0.2)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X_data_array2, y_labels_array, test_size=0.2)
X_train_no_seed, X_test_no_seed, y_train_no_seed, y_test_no_seed = train_test_split(X_data_array, y_labels_array, test_size=0.2)

In [235]:
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.utils.class_weight import compute_class_weight
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import MinMaxScaler


In [236]:
y_train_one_hot = tf.keras.utils.to_categorical(y_train, num_classes=9)
y_train_one_hot = tf.keras.utils.to_categorical(y_train_no_seed, num_classes=9)
#class_weights = compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)
class_weights_dict = {0.0: 0.01, 1.0: 2.0, 2.0: 2.0, 3.0: 4.0, 4.0: 8.0, 5.0: 16.0, 6.0: 32.0, 7.0: 64.0, 8.0: 128.0}
#class_weight_dict = dict(zip(np.unique(y_train), class_weights))
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


model = models.Sequential([
    layers.Input(shape=(63,)),  # Input layer with 4 features
    layers.Dense(9, activation='softmax')  # Output layer with 3 classes (Softmax output)
])
model_no_seed = models.Sequential([
    layers.Input(shape=(62,)),  # Input layer with 4 features
    layers.Dense(9, activation='softmax')  # Output layer with 3 classes (Softmax output)
])

In [237]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])
model.fit(X_train, y_train_one_hot, epochs=100, batch_size=16, class_weight=class_weights_dict)

Epoch 1/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 889us/step - accuracy: 0.0204 - loss: 36.7114 
Epoch 2/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.0198 - loss: 8.6586
Epoch 3/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0239 - loss: 8.0312
Epoch 4/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0263 - loss: 6.9308
Epoch 5/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0295 - loss: 6.5748
Epoch 6/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step - accuracy: 0.0195 - loss: 5.7855
Epoch 7/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0239 - loss: 5.2158  
Epoch 8/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0253 - loss: 5.6326
Epoch 9/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 772us/step - accuracy: 0.0278 - loss: 4.5953
Epoch 10/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.0143 - loss: 5.3486
Epoch 11/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0255 - loss: 4.7458  
Epoch 12/100
177/177 ━━━━

In [238]:
single_sample = tf.expand_dims(X_train[0], axis=0)

# Pass it through the model
output = model(single_sample)
print(output)

tf.Tensor(
[[0.00160134 0.04482429 0.00434229 0.04837518 0.01486966 0.0167531
  0.00679003 0.59832215 0.26412192]], shape=(1, 9), dtype=float32)


In [239]:
scaler = MinMaxScaler()
y_train_one_hot2 = tf.keras.utils.to_categorical(y_train2, num_classes=9)

X_train_scaled2 = scaler.fit_transform(X_train2)
X_test_scaled2 = scaler.transform(X_test2)

print(X_train_scaled2)
print(y_train_one_hot2)

model2 = models.Sequential([
    layers.Input(shape=(17,)),  # Input layer with 4 features
    layers.Dense(9, activation='softmax')  # Output layer with 3 classes (Softmax output)
])

[[0.26285714 0.99       0.02205882 ... 0.6        0.32773109 0.        ]
 [0.66095238 0.505      0.69158497 ... 0.49411765 0.6092437  0.        ]
 [0.50666667 0.42       0.57608252 ... 0.40588235 0.40336134 0.        ]
 ...
 [0.46857143 0.41       0.52992239 ... 0.21176471 0.36134454 0.        ]
 [0.3047619  0.635      0.12520425 ... 0.65294118 0.30672269 0.        ]
 [0.71238095 0.295      0.89511846 ... 0.37058824 0.40336134 0.5625    ]]
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [240]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)
model2.compile(optimizer=optimizer, 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])
model2.fit(X_train_scaled2, y_train_one_hot2, epochs=100, batch_size=16, class_weight=class_weights_dict)

Epoch 1/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 605us/step - accuracy: 0.0657 - loss: 2.7274
Epoch 2/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step - accuracy: 0.0650 - loss: 2.5679
Epoch 3/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 644us/step - accuracy: 0.0845 - loss: 2.0707 
Epoch 4/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.0759 - loss: 2.1032
Epoch 5/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 677us/step - accuracy: 0.2227 - loss: 2.5563
Epoch 6/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.4083 - loss: 2.2683
Epoch 7/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - accuracy: 0.5596 - loss: 2.2440
Epoch 8/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step - accuracy: 0.6201 - loss: 2.5823
Epoch 9/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 628us/step - accuracy: 0.6346 - loss: 2.2105
Epoch 10/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 710us/step - accuracy: 0.7149 - loss: 2.1724
Epoch 11/100
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step - accuracy: 0.6472 - loss: 2.6756
Epoch 12/100
177/1

In [241]:
single_sample = tf.expand_dims(X_train2[0], axis=0)

# Pass it through the model
output = model2(single_sample)
print(output)
print(model2.weights)

tf.Tensor([[1. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(1, 9), dtype=float32)
[<Variable path=sequential_55/dense_65/kernel, shape=(17, 9), dtype=float32, value=[[-8.9030371e+00 -1.7935888e+00 -3.6345479e+00 -2.3542562e+00
  -1.1096926e+00 -9.1230184e-01  8.0325407e-01  1.1981736e+00
   8.4165329e-01]
 [ 1.9435766e+01  5.3904181e+00  4.2724872e+00  4.4735050e+00
   1.8391510e+00  5.3516233e-01  6.2289268e-01 -4.6955695e+00
  -2.2326274e+00]
 [-6.0786071e+00 -5.1233664e+00 -2.5812275e+00 -2.6132898e-02
   1.2049776e-01 -9.3178499e-01 -2.4142683e-01  1.1472633e+00
   3.1381413e-01]
 [-3.7789969e+00 -2.2111039e+00 -9.3002969e-01 -9.2077273e-01
  -8.8559091e-01  1.6303429e-01  5.2402741e-01  4.7712487e-01
  -9.7913778e-01]
 [ 2.6893225e+00  9.4257289e-01  2.5889900e-01 -2.0826466e-01
  -6.0983205e-01  4.7582707e-01 -1.5841672e+00 -1.3889171e+00
   1.9498370e+00]
 [ 9.2327852e+00  6.8515247e-01  1.7488031e+00  1.1001562e+00
   1.1627243e+00  3.8494182e-01  1.5561980e+00 -3.7273662e+00
  -3.9321595

In [242]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [243]:
y_train = y_train.astype(int)

In [244]:
y_train_binary = (y_train2 != 0.0).astype(int)

# Train-test split
X_train_step1, X_test_step1, y_train_step1, y_test_step1 = train_test_split(X_train2, y_train_binary, test_size=0.2, random_state=42)

# Train Logistic Regression
log_reg = LogisticRegression(class_weight='balanced', max_iter=1000)
log_reg.fit(X_train_step1, y_train_step1)

# Evaluate
y_pred_step1 = log_reg.predict(X_test_step1)
print(classification_report(y_test_step1, y_pred_step1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       456
           1       1.00      1.00      1.00       108

    accuracy                           1.00       564
   macro avg       1.00      1.00      1.00       564
weighted avg       1.00      1.00      1.00       564



In [245]:
X_train_step1.shape

(2254, 17)

In [246]:
def anomaly_detection(x_input, model):
    return model.predict([x_input])

In [247]:
X_train_step2 = X_train2[y_train != 0]
y_train_step2 = y_train[y_train != 0]

In [248]:
y_train_one_hot = tf.one_hot(y_train_step2 - 1, depth=8)  # Classes 1-8 become indices 0-7
y_test_one_hot = tf.one_hot(y_test[y_test != 0] - 1, depth=8)

# Define the neural network
input_dim = 17  # Number of features in your input data
model = tf.keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=(input_dim,)),  # Input layer with 17 features
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(8, activation='softmax')  # 8 output classes (1-8)
])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train_step2, y_train_one_hot, epochs=20, batch_size=32, validation_split=0.2)

# Evaluate the model
model.evaluate(X_test[y_test != 0], y_test_one_hot)


Epoch 1/20


/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.2295 - loss: 13.7600 - val_accuracy: 0.4537 - val_loss: 2.5171
Epoch 2/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.2608 - loss: 3.1408 - val_accuracy: 0.4259 - val_loss: 2.2574
Epoch 3/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3399 - loss: 2.3396 - val_accuracy: 0.2963 - val_loss: 1.8245
Epoch 4/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3033 - loss: 1.9078 - val_accuracy: 0.4722 - val_loss: 1.7653
Epoch 5/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3875 - loss: 1.8572 - val_accuracy: 0.4815 - val_loss: 1.6720
Epoch 6/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3199 - loss: 1.7953 - val_accuracy: 0.5093 - val_loss: 1.8363
Epoch 7/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3411 - loss: 1.8769 - val_accuracy: 0.4167 - val_loss: 1.7604
Epoch 8/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3083 - loss: 1.8258 - val_accuracy: 0.5185 - val_loss: 1.8501
E

2024-12-05 03:03:57.080459: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: INVALID_ARGUMENT: Matrix size-incompatible: In[0]: [32,63], In[1]: [17,128]
	 [[{{function_node __inference_one_step_on_data_2512221}}{{node sequential_56_1/dense_66_1/Relu}}]]


InvalidArgumentError: Graph execution error:

Detected at node sequential_56_1/dense_66_1/Relu defined at (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "/Users/liufamily/Library/Python/3.11/lib/python/site-packages/ipykernel_launcher.py", line 17, in <module>

  File "/Users/liufamily/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py", line 1043, in launch_instance

  File "/Users/liufamily/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelapp.py", line 728, in start

  File "/Users/liufamily/Library/Python/3.11/lib/python/site-packages/tornado/platform/asyncio.py", line 195, in start

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 607, in run_forever

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 80, in _run

  File "/Users/liufamily/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 516, in dispatch_queue

  File "/Users/liufamily/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 505, in process_one

  File "/Users/liufamily/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 412, in dispatch_shell

  File "/Users/liufamily/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 740, in execute_request

  File "/Users/liufamily/Library/Python/3.11/lib/python/site-packages/ipykernel/ipkernel.py", line 422, in do_execute

  File "/Users/liufamily/Library/Python/3.11/lib/python/site-packages/ipykernel/zmqshell.py", line 540, in run_cell

  File "/Users/liufamily/Library/Python/3.11/lib/python/site-packages/IPython/core/interactiveshell.py", line 3009, in run_cell

  File "/Users/liufamily/Library/Python/3.11/lib/python/site-packages/IPython/core/interactiveshell.py", line 3064, in _run_cell

  File "/Users/liufamily/Library/Python/3.11/lib/python/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner

  File "/Users/liufamily/Library/Python/3.11/lib/python/site-packages/IPython/core/interactiveshell.py", line 3269, in run_cell_async

  File "/Users/liufamily/Library/Python/3.11/lib/python/site-packages/IPython/core/interactiveshell.py", line 3448, in run_ast_nodes

  File "/Users/liufamily/Library/Python/3.11/lib/python/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code

  File "/var/folders/q0/hn6y49dn3qlbbv0j58dc42tm0000gn/T/ipykernel_39806/4194306141.py", line 20, in <module>

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py", line 481, in evaluate

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py", line 216, in function

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py", line 129, in multi_step_on_iterator

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py", line 110, in one_step_on_data

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py", line 87, in test_step

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/layers/layer.py", line 899, in __call__

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/ops/operation.py", line 46, in __call__

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 156, in error_handler

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/models/sequential.py", line 213, in call

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/models/functional.py", line 182, in call

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/ops/function.py", line 171, in _run_through_graph

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/models/functional.py", line 632, in call

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/layers/layer.py", line 899, in __call__

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/ops/operation.py", line 46, in __call__

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 156, in error_handler

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/layers/core/dense.py", line 148, in call

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/activations/activations.py", line 47, in relu

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/activations/activations.py", line 101, in static_call

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/backend/tensorflow/nn.py", line 15, in relu

Matrix size-incompatible: In[0]: [32,63], In[1]: [17,128]
	 [[{{node sequential_56_1/dense_66_1/Relu}}]] [Op:__inference_multi_step_on_iterator_2512246]

In [ ]:
def hierarchical_classifier(x_input, anomaly_model, multiclass_models):
    # Step 1: Anomaly Detection
    is_anomalous = anomaly_detection(x_input, anomaly_model)
    if is_anomalous == 0:
        return 0  # Class 0

    # Step 2: Multiclass Classification (ensemble or pick one)
    rf_pred = multiclass_models['rf'].predict([x_input])[0]
    svm_pred = multiclass_models['svm'].predict([x_input])[0]
    nn_pred = multiclass_models['nn'].predict([x_input]).argmax()

    # Combine predictions or use a voting strategy
    return rf_pred